import { createClientFromRequest } from 'npm:@base44/sdk@0.8.21';

const ORPHANED_CODES = [
  "PAGE_HELP_REGISTRY", "PAGE_ACA_LIBRARY", "PAGE_HELP_DASHBOARD",
  "PAGE_HELP_MANUAL", "PAGE_HELP_ANALYTICS", "PAGE_HELP_COVERAGE",
  "PAGE_HELP_ADMIN", "PAGE_HELP_CENTER", "PAGE_SETTINGS",
  "PAGE_INTEGRATION_INFRA", "PAGE_POLICYMATCH", "PAGE_EMPLOYER_PORTAL",
  "PAGE_EMPLOYEE_BENEFITS", "PAGE_EMPLOYEE_ENROLL", "PAGE_EMPLOYEE_LOGIN",
  "PAGE_EMPLOYEE_MGMT", "PAGE_EMPLOYEE_PORTAL", "PAGE_CONTRIBUTIONS",
  "PAGE_EXCEPTIONS", "PAGE_PROPOSALS", "PAGE_PLANS", "PAGE_EMPLOYERS",
  "PAGE_TASKS", "PAGE_RENEWALS", "PAGE_ENROLLMENT", "PAGE_QUOTES",
  "PAGE_CENSUS", "PAGE_CASE_DETAIL", "PAGE_CASE_NEW", "PAGE_CASES",
  "PAGE_DASHBOARD",
  "CRD-ADM-HELP-DASHBOARD-KPI-TOTAL-TARGETS",
  "GRID-ADM-HELP-DASHBOARD-MODULE-COVERAGE",
  "CRD-ADM-HELP-DASHBOARD-KPI-COVERAGE",
  "COL-ADM-HELP-DASHBOARD-MODULE-COVERAGE-PERCENT",
  "GRID-ADM-HELP-TARGETS-REGISTRY",
  "BTN-ADM-HELP-DASHBOARD-VIEW-COVERAGE",
  "BTN-ADM-HELP-TARGETS-ROW-EDIT",
  "FLD-ADM-HELP-CONTENT-EXPECTED-ACTION",
  "FLD-ADM-HELP-CONTENT-TARGET-CODE",
  "FLD-ADM-HELP-CONTENT-HELP-TITLE",
  "FLD-ADM-HELP-TARGETS-FILTER-PAGE",
  "FLD-ADM-HELP-CONTENT-ALLOWED-VALUES",
  "FLD-ADM-HELP-CONTENT-SHORT-HELP",
  "BTN-ADM-HELP-TARGETS-APPLY-FILTERS",
  "COL-ADM-HELP-TARGETS-REGISTRY-TARGET-CODE",
  "FLD-ADM-HELP-CONTENT-DETAILED-HELP",
  "BTN-ADM-HELP-TARGETS-ROW-CREATE",
  "FLD-ADM-HELP-CONTENT-CAPABILITIES",
  "COL-ADM-HELP-DASHBOARD-MODULE-COVERAGE-NAME",
  "COL-ADM-HELP-TARGETS-REGISTRY-TYPE",
  "FLD-ADM-HELP-TARGETS-FILTER-TYPE",
  "CRD-ADM-HELP-DASHBOARD-KPI-MISSING",
  "FLD-ADM-HELP-TARGETS-FILTER-MODULE",
  "BTN-ADM-HELP-CONTENT-SAVE-DRAFT",
  "BTN-ADM-HELP-CONTENT-ACTIVATE",
  "FLD-ADM-HELP-CONTENT-WARNINGS",
  "TAB-ADM-HELP-CONTENT-PREVIEW-MANUAL",
  "GRID-ADM-HELP-COVERAGE-PAGE",
  "TAB-ADM-HELP-CONTENT-PREVIEW-MODAL",
  "FLD-ADM-HELP-MANUAL-TOPIC-BODY",
  "GRID-ADM-HELP-MANUAL-TARGET-MAP",
  "GRID-ADM-HELP-COVERAGE-MODULE",
  "GRID-ADM-HELP-COVERAGE-MISSING",
  "BTN-ADM-HELP-COVERAGE-EXPORT",
  "FLD-ADM-HELP-MANUAL-TOPIC-CODE",
  "GRID-ADM-HELP-MANUAL-TREE",
  "BTN-ADM-HELP-MANUAL-PUBLISH",
  "FLD-ADM-HELP-AI-REVIEW-STATUS-FILTER",
  "CRD-ADM-HELP-COVERAGE-COVERED",
  "FLD-ADM-HELP-MANUAL-TOPIC-TITLE",
  "CRD-ADM-HELP-COVERAGE-TOTAL",
  "GRID-ADM-HELP-CONTENT-VERSIONS",
  "FLD-ADM-HELP-AI-REVIEW-QUESTION",
  "GRID-ADM-HELP-ANALYTICS-TOPICS",
  "FLD-ADM-HELP-AI-REVIEW-ANSWER",
  "GRID-ADM-HELP-AI-REVIEW-GRID",
  "BTN-ADM-HELP-AI-REVIEW-MARK-RESOLVED",
  "GRID-ADM-HELP-ANALYTICS-TOP-SEARCHES",
  "FLD-ADM-HELP-AI-REVIEW-CONFIDENCE-FILTER",
  "BTN-ADM-HELP-AI-REVIEW-CREATE-HELP",
  "GRID-ADM-HELP-ANALYTICS-ZERO-RESULTS",
  "FLD-EMP-DETAIL-PERSONAL-FIRST-NAME",
  "FLD-CLAIMS-LIST-FILTER-STATUS",
  "GRID-USR-HELP-MANUAL-RELATED",
  "BTN-USR-HELP-MANUAL-ASK-AI",
  "GRID-USR-HELP-MANUAL-NAV",
  "BTN-EMP-DETAIL-HEADER-SAVE",
  "BTN-EMP-DETAIL-HEADER-CANCEL",
  "FLD-EMP-DETAIL-PERSONAL-LAST-NAME",
  "FLD-EMP-DETAIL-EMPLOYMENT-STATUS",
  "FLD-USR-HELP-MANUAL-SEARCH",
  "FLD-EMP-DETAIL-PERSONAL-EMAIL",
  "FLD-USR-HELP-MANUAL-TOPIC-TITLE",
  "FLD-CLAIMS-LIST-FILTER-MEMBER",
  "GRID-ADM-HELP-ANALYTICS-TARGETS",
  "FLD-SETTINGS-NOTIFICATIONS-CHANNELS-FROM-EMAIL",
  "GRID-CLAIMS-LIST-GRID",
  "FLD-SETTINGS-NOTIFICATIONS-GENERAL-ENABLE-SMS",
  "ACT-CLAIMS-LIST-GRID-VIEW-DETAIL",
  "FLD-SETTINGS-NOTIFICATIONS-GENERAL-ENABLE-EMAIL",
  "COL-CLAIMS-LIST-GRID-STATUS",
  "BTN-RENEWAL-CASE-HEADER-SAVE",
  "COL-CLAIMS-LIST-GRID-CLAIM-NUMBER",
  "FLD-RENEWAL-CASE-APPROVAL-DECISION",
  "BTN-RENEWAL-CASE-APPROVAL-SUBMIT",
  "FLD-RENEWAL-CASE-SUMMARY-STATUS",
  "BTN-SETTINGS-NOTIFICATIONS-SAVE",
  "CMP-GLOBAL-CONTEXT-HELP-MODAL",
  "CMP-GLOBAL-HELP-AI-LAUNCHER",
  "TEST.FIELD",
];

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (user?.role !== 'admin') {
      return Response.json({ error: 'Forbidden: Admin access required' }, { status: 403 });
    }

    let deleted = 0;
    let failed = 0;

    for (const code of ORPHANED_CODES) {
      try {
        const records = await base44.entities.HelpContent.filter({ help_target_code: code });
        for (const record of records) {
          await base44.entities.HelpContent.delete(record.id);
          deleted++;
          // Small delay to avoid rate limiting
          await new Promise(resolve => setTimeout(resolve, 100));
        }
      } catch (err) {
        console.warn(`Failed to delete content for ${code}:`, err.message);
        failed++;
      }
      // Batch delay every 5 codes
      if (ORPHANED_CODES.indexOf(code) % 5 === 0) {
        await new Promise(resolve => setTimeout(resolve, 500));
      }
    }

    return Response.json({ deleted, failed, totalAttempted: ORPHANED_CODES.length });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});