export const CENSUS_FIELDS = [
  { key: "first_name", label: "First Name", required: true },
  { key: "last_name", label: "Last Name", required: true },
  { key: "date_of_birth", label: "Date of Birth", required: false },
  { key: "gender", label: "Gender", required: false },
  { key: "email", label: "Email", required: false },
  { key: "phone", label: "Phone", required: false },
  { key: "employee_id", label: "Employee ID", required: false },
  { key: "ssn_last4", label: "SSN Last 4", required: false },
  { key: "hire_date", label: "Hire Date", required: false },
  { key: "employment_status", label: "Emp. Status", required: false },
  { key: "employment_type", label: "Emp. Type", required: false },
  { key: "hours_per_week", label: "Hours/Week", required: false },
  { key: "annual_salary", label: "Annual Salary", required: false },
  { key: "job_title", label: "Job Title", required: false },
  { key: "department", label: "Department", required: false },
  { key: "address", label: "Address", required: false },
  { key: "city", label: "City", required: false },
  { key: "state", label: "State", required: false },
  { key: "zip", label: "Zip Code", required: false },
  { key: "coverage_tier", label: "Coverage Tier", required: false },
  { key: "dependent_count", label: "Dependent Count", required: false },
  { key: "class_code", label: "Class Code", required: false },
];

export const CENSUS_ALLOWED_MEMBER_FIELDS = CENSUS_FIELDS.map((field) => field.key).concat([
  "census_version_id",
  "case_id",
  "is_eligible",
  "validation_status",
  "validation_issues",
]);

export const CENSUS_AUTOMAP_HINTS = {
  first_name: ["first_name", "first name", "firstname", "fname", "given name", "given_name"],
  last_name: ["last_name", "last name", "lastname", "lname", "surname", "family name"],
  date_of_birth: ["date_of_birth", "dob", "birth date", "birthdate", "birth_date", "date of birth"],
  gender: ["gender", "sex"],
  email: ["email", "email address", "e-mail", "work email"],
  phone: ["phone", "phone number", "mobile", "cell", "telephone"],
  employee_id: ["employee_id", "emp id", "emp_id", "employee id", "staff id"],
  ssn_last4: ["ssn", "ssn4", "ssn_last4", "last 4", "last4", "social security"],
  hire_date: ["hire_date", "hire date", "start date", "start_date", "date hired"],
  employment_status: ["employment_status", "emp status", "status", "active"],
  employment_type: ["employment_type", "emp type", "type", "full time", "part time"],
  hours_per_week: ["hours", "hours_per_week", "hours per week", "weekly hours"],
  annual_salary: ["salary", "annual_salary", "annual salary", "compensation", "wage"],
  job_title: ["job_title", "title", "position", "job title", "role"],
  department: ["department", "dept", "division", "team"],
  address: ["address", "street", "address1", "street address"],
  city: ["city", "town"],
  state: ["state", "st", "province"],
  zip: ["zip", "zip_code", "postal", "postal_code", "zipcode"],
  coverage_tier: ["coverage_tier", "coverage", "tier", "plan tier", "coverage type"],
  dependent_count: ["dependents", "dependent_count", "dep count"],
  class_code: ["class", "class_code", "employee class", "grade"],
};