import type { FeatureInventoryItem } from "../shared/documentation_types";

export const FeatureInventorySeed: FeatureInventoryItem[] = [
  {
    feature_code: "FEAT-ADM-001",
    feature_name: "Open User Management",
    page_code: "SCR-ADM-001",
    feature_type: "action",
    trigger_type: "button_click",
    user_roles: ["Admin"],
    description: "Navigates user to the user management page.",
    input_data: [],
    output_data: [],
    backend_process: "Route navigation only",
    workflow_impact: [],
    notification_impact: [],
    validation_rules: [],
    success_result: "User management page opens",
    failure_conditions: ["Route missing", "Permission denied"],
    dependencies: ["routing", "permissions"],
    audit_logged: true,
  },
  {
    feature_code: "FEAT-ADM-002",
    feature_name: "Create New User",
    page_code: "SCR-ADM-002",
    feature_type: "action",
    trigger_type: "button_click",
    user_roles: ["Admin"],
    description: "Creates a new user account with specified role and permissions.",
    input_data: ["email", "full_name", "role", "permissions"],
    output_data: ["users.id", "users.email", "users.full_name", "users.role"],
    backend_process: "UserService.create() → UserRepository.insert() → AuditLog.record()",
    workflow_impact: [],
    notification_impact: ["WelcomeEmail"],
    validation_rules: ["email required", "email unique", "email valid format", "role in allowed list"],
    success_result: "User created, welcome email sent, redirect to user detail",
    failure_conditions: [
      "Email already exists → show duplicate error",
      "Validation error → show field errors",
      "Permission denied → show access error",
    ],
    dependencies: ["UserService", "EmailService", "AuditLog"],
    audit_logged: true,
  },
];