import type { PageInventoryItem } from "../shared/documentation_types";

export const PageInventorySeed: PageInventoryItem[] = [
  {
    page_code: "SCR-ADM-001",
    page_name: "Admin Dashboard",
    route: "/admin/dashboard",
    parent_page_code: null,
    module: "Administration",
    page_type: "screen",
    access_roles: ["Admin"],
    is_hidden: false,
    entry_points: ["Main Navigation"],
    child_pages: ["SCR-ADM-002"],
    related_workflows: ["WF-ONBOARD-001"],
    related_entities: ["users", "tasks", "notifications"],
    backend_services: ["AdminDashboardService.load"],
    dependencies_inbound: [],
    dependencies_outbound: ["SCR-ADM-002"],
    description: "Primary administration dashboard for system management.",
  },
  {
    page_code: "SCR-ADM-002",
    page_name: "User Management",
    route: "/admin/users",
    parent_page_code: "SCR-ADM-001",
    module: "Administration",
    page_type: "screen",
    access_roles: ["Admin"],
    is_hidden: false,
    entry_points: ["Admin Dashboard Button", "Admin Navigation"],
    child_pages: [],
    related_workflows: [],
    related_entities: ["users"],
    backend_services: ["UserService.list", "UserService.create", "UserService.update"],
    dependencies_inbound: ["SCR-ADM-001"],
    dependencies_outbound: [],
    description: "Manage application users, roles, and permissions.",
  },
];