import type { ManualSectionOutline } from "../shared/documentation_types";

export const WordSectionOutlineSeed: ManualSectionOutline[] = [
  {
    section_code: "SEC-001",
    heading_level: 1,
    title: "Title Page",
    description: "Document title and metadata",
    sort_order: 1,
    is_repeatable: false,
  },
  {
    section_code: "SEC-002",
    heading_level: 1,
    title: "Document Control",
    description: "Purpose, audience, scope, usage",
    sort_order: 2,
    is_repeatable: false,
  },
  {
    section_code: "SEC-003",
    heading_level: 1,
    title: "Revision History",
    description: "Document version history table",
    sort_order: 3,
    is_repeatable: false,
  },
  {
    section_code: "SEC-004",
    heading_level: 1,
    title: "Application Overview",
    description: "System purpose, modules, statistics",
    sort_order: 4,
    is_repeatable: false,
  },
  {
    section_code: "SEC-005",
    heading_level: 1,
    title: "User Roles and Permissions",
    description: "Role definitions and permission matrix",
    sort_order: 5,
    is_repeatable: false,
  },
  {
    section_code: "SEC-006",
    heading_level: 1,
    title: "Navigation Overview",
    description: "Menu structure and page hierarchy",
    sort_order: 6,
    is_repeatable: false,
  },
  {
    section_code: "SEC-007",
    heading_level: 1,
    title: "Page-by-Page Manual",
    description: "Full page documentation",
    sort_order: 10,
    is_repeatable: false,
  },
  {
    section_code: "SEC-008",
    heading_level: 1,
    title: "Control Dictionary",
    description: "Complete control reference",
    sort_order: 20,
    is_repeatable: false,
  },
  {
    section_code: "SEC-009",
    heading_level: 1,
    title: "Workflows and State Transitions",
    description: "All workflows with states and transitions",
    sort_order: 30,
    is_repeatable: false,
  },
  {
    section_code: "SEC-010",
    heading_level: 1,
    title: "Appendices",
    description: "Glossary, shortcuts, dependency maps",
    sort_order: 100,
    is_repeatable: false,
  },
];