/**
 * MGA Phase 4A — Backfill Execution Plan
 * lib/mga/migration/backfillPlan.js
 *
 * Defines the ordered backfill plan for Phase 4B.
 * Phase 4A: plan definition only. No backfill is executed.
 *
 * @see docs/MGA_PHASE_4A_MIGRATION_READINESS_AND_DRY_RUN_REPORT.md Section 4
 */

export const BACKFILL_STEPS = [
  {
    step: 1,
    entity: 'MasterGeneralAgent',
    description: 'Verify MGA seed records are correct; no creation during Phase 4B',
    sourceRecords: 'MasterGeneralAgent entity',
    targetField: null,
    parentDependency: null,
    backfillRule: 'Verify all expected MGAs are present; count matches expected seed',
    validationRule: 'MGA count matches expected; no duplicate codes',
    anomalyHandling: 'Duplicate code → quarantine; alert migration owner',
    rollbackMarker: 'Snapshot all MGA records before any downstream backfill',
    quarantineCondition: 'Duplicate or missing expected MGA',
    acceptanceThreshold: '100% of expected MGAs present',
    indexRequired: [1],
    businessApprovalRequired: true,
  },
  {
    step: 2,
    entity: 'MasterGroup',
    description: 'Apply approved MasterGroup → MGA mapping table',
    sourceRecords: 'MasterGroup entity; approved mapping plan from masterGroupMappingPlan.js',
    targetField: 'master_general_agent_id',
    parentDependency: 'MasterGeneralAgent (Step 1)',
    backfillRule: 'Write approved proposed_mga_id to MasterGroup.master_general_agent_id; mga_migration_status = migrated; mga_migration_batch_id = batch_id',
    validationRule: '100% MasterGroup → MGA reconciliation; count match',
    anomalyHandling: 'Ambiguous or conflicting → quarantine; block downstream',
    rollbackMarker: 'Snapshot master_general_agent_id field before write',
    quarantineCondition: 'No approved mapping after business review',
    acceptanceThreshold: '100% deterministic or quarantined',
    indexRequired: [2],
    businessApprovalRequired: true,
  },
  {
    step: 3,
    entity: 'Tenant',
    description: 'Propagate MGA from parent MasterGroup',
    targetField: 'master_general_agent_id',
    parentDependency: 'MasterGroup (Step 2)',
    backfillRule: 'Read MasterGroup.master_general_agent_id for each Tenant.master_group_id; write to Tenant.master_general_agent_id',
    validationRule: 'Tenant/MasterGroup/MGA count check',
    anomalyHandling: 'Parent MasterGroup unresolved → quarantine Tenant; block downstream',
    rollbackMarker: 'Snapshot before write',
    quarantineCondition: 'Parent MasterGroup not resolved',
    acceptanceThreshold: '100%',
    indexRequired: [17],
    businessApprovalRequired: false,
  },
  {
    step: 4,
    entity: 'EmployerGroup',
    description: 'Propagate MGA from parent MasterGroup via agency_id/master_group_id chain',
    targetField: 'master_general_agent_id',
    parentDependency: 'MasterGroup (Step 2)',
    backfillRule: 'Resolve EmployerGroup → MasterGroup → MGA; write to master_general_agent_id',
    validationRule: 'Employer/MasterGroup/MGA count',
    anomalyHandling: 'No parent → quarantine; block case downstream',
    rollbackMarker: 'Snapshot before write',
    quarantineCondition: 'Parent MasterGroup not resolvable',
    acceptanceThreshold: '≥99%; remainder quarantined',
    indexRequired: [3],
    businessApprovalRequired: false,
  },
  {
    step: 5,
    entity: 'BenefitCase',
    description: 'Propagate MGA from parent EmployerGroup',
    targetField: 'master_general_agent_id',
    parentDependency: 'EmployerGroup (Step 4)',
    backfillRule: 'Read EmployerGroup.master_general_agent_id for each BenefitCase.employer_group_id; write to BenefitCase.master_general_agent_id',
    validationRule: 'Case/Employer/MGA count',
    anomalyHandling: 'No parent EmployerGroup → quarantine case; block census/quote/enrollment downstream',
    rollbackMarker: 'Snapshot before write',
    quarantineCondition: 'Parent EmployerGroup not resolved',
    acceptanceThreshold: '≥99%',
    indexRequired: [4],
    businessApprovalRequired: false,
  },
  {
    step: 6,
    entity: 'CensusVersion + CensusMember',
    description: 'Propagate MGA from parent BenefitCase',
    targetField: 'master_general_agent_id',
    parentDependency: 'BenefitCase (Step 5)',
    backfillRule: 'Propagate from BenefitCase',
    validationRule: 'Version/Member/Case/MGA count',
    anomalyHandling: 'No parent → quarantine',
    rollbackMarker: 'Snapshot before write',
    quarantineCondition: 'Parent BenefitCase not resolved',
    acceptanceThreshold: '≥99%',
    indexRequired: [5, 6],
    businessApprovalRequired: false,
  },
  {
    step: 7,
    entity: 'CensusImportJob + CensusImportAuditEvent + CensusValidationResult',
    description: 'Propagate MGA from BenefitCase chain; cross-check CensusVersion for CensusValidationResult',
    targetField: 'master_general_agent_id',
    parentDependency: 'BenefitCase (Step 5); CensusImportJob (for AuditEvent + ValidationResult)',
    backfillRule: 'Propagate from BenefitCase via case_id; cross-check CensusVersion MGA for CensusValidationResult',
    validationRule: 'Job/Event/Result counts; cross-entity MGA consistency',
    anomalyHandling: 'Orphan or mismatch → quarantine',
    rollbackMarker: 'Snapshot before write',
    quarantineCondition: 'Orphan or cross-entity MGA mismatch',
    acceptanceThreshold: '≥99%',
    indexRequired: [18, 19, 20],
    businessApprovalRequired: false,
    note: 'After successful Phase 4B backfill and validation, CensusImportJob, CensusImportAuditEvent, and CensusValidationResult may be removed from SCOPE_PENDING_ENTITY_TYPES in a separate approved step.',
  },
  {
    step: 8,
    entity: 'QuoteScenario + ScenarioPlan + ContributionModel + QuoteTransmission + PolicyMatchResult',
    description: 'Propagate MGA from BenefitCase',
    targetField: 'master_general_agent_id',
    parentDependency: 'BenefitCase (Step 5)',
    backfillRule: 'Propagate from BenefitCase',
    validationRule: 'Quote/Scenario/MGA count',
    anomalyHandling: 'No parent → quarantine',
    rollbackMarker: 'Snapshot before write',
    quarantineCondition: 'Parent BenefitCase not resolved',
    acceptanceThreshold: '≥99%',
    indexRequired: [7],
    businessApprovalRequired: false,
  },
  {
    step: 9,
    entity: 'Proposal',
    description: 'Propagate MGA from BenefitCase; review PDF artifacts',
    targetField: 'master_general_agent_id',
    parentDependency: 'BenefitCase (Step 5)',
    backfillRule: 'Propagate from BenefitCase; flag generated PDF artifacts for review',
    validationRule: 'Proposal/Case/MGA count; PDF artifact review',
    anomalyHandling: 'No parent → quarantine; revoke PDF artifact if generated',
    rollbackMarker: 'Snapshot before write + artifact snapshot',
    quarantineCondition: 'Parent not resolved; or PDF contains cross-MGA data',
    acceptanceThreshold: '≥99%; PDF artifacts reviewed',
    indexRequired: [15],
    businessApprovalRequired: true,
  },
  {
    step: 10,
    entity: 'TxQuoteCase + all TXQuote child entities',
    description: 'Propagate MGA from BenefitCase (100% required)',
    targetField: 'master_general_agent_id',
    parentDependency: 'BenefitCase (Step 5)',
    backfillRule: 'Propagate from BenefitCase; cascade to all TXQuote child entities',
    validationRule: 'TxQuoteCase/BenefitCase/MGA count; 100% resolution required',
    anomalyHandling: 'No parent → quarantine; pause TXQuote flow',
    rollbackMarker: 'Snapshot before write',
    quarantineCondition: 'Parent BenefitCase not resolved',
    acceptanceThreshold: '100% — external transmission records require full resolution',
    indexRequired: [29],
    businessApprovalRequired: true,
  },
  {
    step: 11,
    entity: 'EnrollmentWindow + EmployeeEnrollment + EnrollmentMember',
    description: 'Propagate MGA from BenefitCase chain',
    targetField: 'master_general_agent_id',
    parentDependency: 'BenefitCase (Step 5)',
    backfillRule: 'Propagate from BenefitCase → EnrollmentWindow → EmployeeEnrollment → EnrollmentMember',
    validationRule: 'Enrollment/Window/Member/MGA count',
    anomalyHandling: 'No parent → quarantine; revoke access links for EmployeeEnrollment',
    rollbackMarker: 'Snapshot before write',
    quarantineCondition: 'Parent not resolved',
    acceptanceThreshold: '≥99%; links reviewed',
    indexRequired: [8, 9, 30],
    businessApprovalRequired: false,
  },
  {
    step: 12,
    entity: 'Document',
    description: 'Propagate MGA from BenefitCase (prefer) or EmployerGroup fallback',
    targetField: 'master_general_agent_id',
    parentDependency: 'BenefitCase (Step 5) or EmployerGroup (Step 4)',
    backfillRule: 'Try BenefitCase first; fall back to EmployerGroup; if both missing → quarantine + revoke file_url',
    validationRule: 'Doc/Case/Employer/MGA count',
    anomalyHandling: 'Both parents missing → quarantine; revoke file_url access',
    rollbackMarker: 'Snapshot before write + file access snapshot',
    quarantineCondition: 'Both parents unresolved',
    acceptanceThreshold: '≥99%; file_url reviewed',
    indexRequired: [10],
    businessApprovalRequired: true,
  },
  {
    step: 13,
    entity: 'RenewalCycle + CaseTask + ExceptionItem',
    description: 'Propagate MGA from BenefitCase',
    targetField: 'master_general_agent_id',
    parentDependency: 'BenefitCase (Step 5)',
    backfillRule: 'Propagate from BenefitCase',
    validationRule: 'Renewal/Task/Exception/MGA count',
    anomalyHandling: 'No parent → quarantine',
    rollbackMarker: 'Snapshot before write',
    quarantineCondition: 'Parent not resolved',
    acceptanceThreshold: '≥99%',
    indexRequired: [11, 12, 14],
    businessApprovalRequired: false,
  },
  {
    step: 14,
    entity: 'ActivityLog',
    description: 'Propagate MGA from BenefitCase; null MGA acceptable for platform-admin events',
    targetField: 'master_general_agent_id',
    parentDependency: 'BenefitCase (Step 5)',
    backfillRule: 'Propagate from BenefitCase; if no parent and actor is platform_admin → null MGA acceptable',
    validationRule: 'Log/Case/MGA count',
    anomalyHandling: 'Operational log with no case and non-admin actor → quarantine',
    rollbackMarker: 'Snapshot before write',
    quarantineCondition: 'Operational orphan (no case, non-admin actor)',
    acceptanceThreshold: '≥95% resolved; remainder classified as platform',
    indexRequired: [13],
    businessApprovalRequired: false,
  },
  {
    step: 15,
    entity: 'HelpSearchLog + HelpAIQuestionLog + HelpAuditLog',
    description: 'Resolve MGA from actor user_email via MasterGeneralAgentUser',
    targetField: 'master_general_agent_id',
    parentDependency: 'MasterGeneralAgentUser membership (Step 1 prereq)',
    backfillRule: 'Resolve user_email → MasterGeneralAgentUser → MGA; null MGA acceptable for unauthenticated sessions',
    validationRule: 'User/MGA resolution coverage',
    anomalyHandling: 'Operational event with no user MGA → quarantine or classify as platform',
    rollbackMarker: 'Snapshot before write',
    quarantineCondition: 'Operational event with no resolvable actor MGA',
    acceptanceThreshold: '≥95% classified (resolved or platform); 100% for HelpSearchLog/HelpAIQuestionLog',
    indexRequired: [22, 23, 25, 27],
    businessApprovalRequired: false,
  },
  {
    step: 16,
    entity: 'UserManual + HelpCoverageSnapshot + HelpAITrainingQueue',
    description: 'Classify scope_type; set MGA only for mga_scoped records',
    targetField: 'master_general_agent_id + scope_type',
    parentDependency: 'Classification logic (generating context)',
    backfillRule: 'Classify all existing records as platform_global or mga_scoped; for mga_scoped, set master_general_agent_id',
    validationRule: 'Classification coverage 100%',
    anomalyHandling: 'Unclassifiable → quarantine; hide from MGA users',
    rollbackMarker: 'Snapshot scope_type + MGA before write',
    quarantineCondition: 'Unclassifiable',
    acceptanceThreshold: '100% classified',
    indexRequired: [21, 24, 26],
    businessApprovalRequired: false,
  },
  {
    step: 17,
    entity: 'CaseFilterPreset + ViewPreset',
    description: 'Resolve MGA from user_email via MasterGeneralAgentUser',
    targetField: 'master_general_agent_id',
    parentDependency: 'MasterGeneralAgentUser membership',
    backfillRule: 'Resolve user → MGA; null MGA for unauthenticated',
    validationRule: 'Preset/User/MGA count',
    anomalyHandling: 'Operational preset with no user MGA → quarantine if truly operational; null if unauthenticated',
    rollbackMarker: 'Snapshot before write',
    quarantineCondition: 'Operational preset with no resolvable user MGA',
    acceptanceThreshold: '100% classified',
    indexRequired: [27],
    businessApprovalRequired: false,
  },
  {
    step: 18,
    entity: 'RateSetAssignment + QuoteProviderRoute + TxQuoteDestinationRule',
    description: 'Classify global vs scoped; propagate only for scoped',
    targetField: 'master_general_agent_id',
    parentDependency: 'Business classification approval',
    backfillRule: 'Classify by assignment_type; global → exclude (null MGA); custom → propagate from MGA owner',
    validationRule: 'Classification coverage; scoped/global count',
    anomalyHandling: 'Scoped without owner → quarantine',
    rollbackMarker: 'Classification snapshot before write',
    quarantineCondition: 'Unclassified scoped record',
    acceptanceThreshold: '100% classified after business approval',
    indexRequired: [],
    businessApprovalRequired: true,
  },
  {
    step: 19,
    entity: 'Tenant (scope_type entities — additional pass)',
    description: 'Verify all scope_type discriminators are set correctly post-backfill',
    targetField: 'scope_type',
    parentDependency: 'Steps 16 and above',
    backfillRule: 'Scan all scope_type entities; ensure no null values remain; default unset to platform_global',
    validationRule: 'scope_type null count = 0',
    anomalyHandling: 'Remaining null scope_type → flag as missing_scope_type_discriminator P1',
    rollbackMarker: 'Snapshot before write',
    quarantineCondition: 'N/A — P1 only',
    acceptanceThreshold: '100% scope_type set',
    indexRequired: [],
    businessApprovalRequired: false,
  },
  {
    step: 20,
    entity: 'ALL ENTITIES — final reconciliation pass',
    description: 'Full reconciliation report generated and reviewed before Phase 4B sign-off',
    targetField: null,
    parentDependency: 'All prior steps',
    backfillRule: 'Run reconciliation report; confirm all acceptance thresholds met; P0 anomaly count = 0',
    validationRule: 'All 14 acceptance thresholds met',
    anomalyHandling: 'Any remaining P0 → block sign-off; must resolve before Phase 4B complete',
    rollbackMarker: 'Final snapshot of all backfilled counts',
    quarantineCondition: 'P0 anomaly remaining after all steps',
    acceptanceThreshold: 'All 14 thresholds from Section 10 of Phase 4A report',
    indexRequired: [],
    businessApprovalRequired: true,
  },
];

export default { BACKFILL_STEPS };